/*
 * This file is generated by jOOQ.
 */
package fi.jubic.snoozy.example.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1056759783;

    private Long   id;
    private String name;
    private String role;
    private String hash;
    private String salt;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.role = value.role;
        this.hash = value.hash;
        this.salt = value.salt;
    }

    public User(
        Long   id,
        String name,
        String role,
        String hash,
        String salt
    ) {
        this.id = id;
        this.name = name;
        this.role = role;
        this.hash = hash;
        this.salt = salt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(role);
        sb.append(", ").append(hash);
        sb.append(", ").append(salt);

        sb.append(")");
        return sb.toString();
    }
}
