/*
 * This file is generated by jOOQ.
 */
package fi.jubic.resteasy.example.db.tables.daos;


import fi.jubic.resteasy.example.db.tables.User;
import fi.jubic.resteasy.example.db.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, fi.jubic.resteasy.example.db.tables.pojos.User, Long> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, fi.jubic.resteasy.example.db.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, fi.jubic.resteasy.example.db.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.jubic.resteasy.example.db.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.jubic.resteasy.example.db.tables.pojos.User> fetchById(Long... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.jubic.resteasy.example.db.tables.pojos.User fetchOneById(Long value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<fi.jubic.resteasy.example.db.tables.pojos.User> fetchByName(String... values) {
        return fetch(User.USER.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public fi.jubic.resteasy.example.db.tables.pojos.User fetchOneByName(String value) {
        return fetchOne(User.USER.NAME, value);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<fi.jubic.resteasy.example.db.tables.pojos.User> fetchByRole(String... values) {
        return fetch(User.USER.ROLE, values);
    }

    /**
     * Fetch records that have <code>hash IN (values)</code>
     */
    public List<fi.jubic.resteasy.example.db.tables.pojos.User> fetchByHash(String... values) {
        return fetch(User.USER.HASH, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<fi.jubic.resteasy.example.db.tables.pojos.User> fetchBySalt(String... values) {
        return fetch(User.USER.SALT, values);
    }
}
